### ISSUE TITLE
buttons on Prompt Gallery don't work (AxiosError: Network Error)

### ISSUE THREAD

**Issue by charliehaydenhicks** [dr413677671/PromptGallery-stable-diffusion-webui#11]
Thanks for the great feature set. I'm dying to get this working.

I managed to get this working all the way up until the point where I click "send to webui" or "copy negatives" or any of  those buttons. They all return this error in the console:

```
AxiosError: Network Error
    at u.onerror (http://localhost:5173/assets/index.bed48b02.js:42:4558)
```

I did use the command prompts as described (cors, api). Any thoughts appreciated

**Comment by charliehaydenhicks** [comment]
I forgot to mention that the terminal didn't do anything, so nothing to copy/paste from there. Just the chrome terminal.

**Comment by dr413677671** [comment]
@charliehaydenhicks  Thanks for sending the issue.

Did you use remotely?

If using remotly add parmas like this: --cors-allow-origins http://remote-ip:5173/ --api --listen --server-name remote-ip

**Comment by charliehaydenhicks** [comment]
No, was local only. Do you think it could have something to do with certificates/https?

**Comment by dr413677671** [comment]
Maybe port 5173 closed?

**Comment by dr413677671** [comment]
I just noticed that you mentioned you use it on Colab. Please make sure you could visit port 5173.

**Comment by charliehaydenhicks** [comment]
This was actually on my home machine. Port 5173 was available to me (i.e. going to localhost:5173 resolved to the extension page). Also, the extension page loads when running the webui, it's only when you click on the buttons at the bottom of the page that it doesn't do anything.

Maybe there's something preventing the app from accessing 5173, how could I check that?

**Comment by charliehaydenhicks** [comment]
Just to be clear: this was not on Colab. It was a local install (not a jupyter notebook).

This might not be a cors issue, I think it might be an iFrames permissions issue. The page loads, and it's able to read the thumbnail file from the /preview/ folder, this wasn't happening in colab. I think because of cors issues.

On the local machine, I think cors is working, it just doesn't do anything when clicking the button. I fixed this problem for the copy/paste buttons (by changing the iFrame permissions in the html file). But I don't know what to try for the other buttons.

**Comment by charliehaydenhicks** [comment]
Digging a little more. Found this issue\ in the console:
ICookie samesite not set: Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
- Cookies affected (are these your cookies?)
  1. _xsrf | localhost/
  2. username-localhost-8888 | localhost/

**Comment by charliehaydenhicks** [comment]
please also add `allow="clipboard-read; clipboard-write"` to the iframe tags

**Comment by dr413677671** [comment]
CORS should be workaround by add param  --cors-allow-origins http://localhost:5173/ to webui

**Comment by dr413677671** [comment]
Thanks! I added allow="clipboard-read; clipboard-write" . Unblock the copy and paste now. But I still do not understand why I could not repro:
AxiosError: Network Error
    at u.onerror (http://localhost:5173/assets/index.bed48b02.js:42:4558)

**Comment by dr413677671** [comment]
I think 8888 might be your local jupyter notebook. This is not affected.

Web page do not store cookies. Web browser does. I checked the code of xsrf. Axios requests an xsrf protected action from http://'+ip+':'+port+'/sdapi/v1/txt2img' via a POST request. This happens when calling web-ui API.

From your description.  It might be your browser setting that block this activity. One assumption is your are using browser like firefox which has a STRICT samesite config. Try lower ths level or use chrome. I dont th

**Comment by charliehaydenhicks** [comment]
I think I found it!!!! Webui is running on 127.0.0.1 and the extension is runnning on localhost. Apparently Chrome thinks these are different domains! 

I'll see if I can figure out how to run webui on localhost and see if that fixes it.

![image](https://user-images.githubusercontent.com/120376254/208263743-ce743591-d6ed-4025-8866-866c79f8ed83.png)

**Comment by charliehaydenhicks** [comment]
Okay, I added the flag --listen to the command arguments. The error message changed slightly but the main error remains.

I think it's because the extension is running on http and automatic1111 webui is running on https. If I can figure out how to change either one of them I think it will work.

Any ideas?

Edit: --listen did change both domains to `localhost`
edit: but it didn't change to https

**Comment by charliehaydenhicks** [comment]
Okay, I'm pretty sure the issue is the cookies from your extension aren't https. 
![image](https://user-images.githubusercontent.com/120376254/208353387-72f73705-3b29-45f9-be03-ea6f6c69011e.png)
![image](https://user-images.githubusercontent.com/120376254/208353466-0c43deea-01c5-47c0-806d-085d6d0e3ee6.png)

**Comment by dr413677671** [comment]
I could not use https since webui is not https. Do you by any chance know how to make it work?

**Comment by dr413677671** [comment]
On my env. AUTOMATIC1111 webui run in http
![image](https://user-images.githubusercontent.com/32362729/209118177-82eb2264-3ac7-4b41-8c0c-65abeb4674cc.png)

**Comment by muunkky** [comment]
Interesting, mine runs in https automatically. I wish I could get it to run in http

**Comment by dr413677671** [comment]
Could you try alter param http in [this line](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/e7f2f1e1b6f9d616d2b207e596df859d909ab31b/modules/api/api.py#L507).

**Comment by dr413677671** [comment]
<img width="406" alt="cors" src="https://user-images.githubusercontent.com/32362729/212533558-280f37aa-125f-40da-a760-3c1a68d92a31.png">
@muunkky  @charliehaydenhicks 
I added some instructions in Readme on how to update the ip and port. 
Please upgrade the extension and follow the exeact instructions. I checked that webui do not add any setup to contraint it to https/http. This might be a environment issue. Clould service might redirect http to https.

It is not considered as an extension issue as running locally it is good.
